// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/home","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"首页","path":"/home","icon":"HomeOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"管理员","path":"/admin","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"管理员列表","path":"adminList","parentId":"3","id":"4"},"5":{"name":"添加管理员","path":"addAdmin","parentId":"3","id":"5"},"6":{"name":"用户","path":"/user","parentId":"ant-design-pro-layout","id":"6"},"7":{"name":"书籍","path":"/book","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"面试题","path":"/interview","parentId":"ant-design-pro-layout","id":"8"},"9":{"name":"问答","path":"/issue","parentId":"ant-design-pro-layout","id":"9"},"10":{"name":"评论","path":"/comment","parentId":"ant-design-pro-layout","id":"10"},"11":{"name":"类型","path":"/type","parentId":"ant-design-pro-layout","id":"11"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Home__index" */'@/pages/Home/index.jsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Admin__index" */'@/pages/Admin/index.jsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Admin__addAdmin" */'@/pages/Admin/addAdmin.jsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__User__index" */'@/pages/User/index.jsx')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Book__index" */'@/pages/Book/index.jsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Interview__index" */'@/pages/Interview/index.jsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Issue__index" */'@/pages/Issue/index.jsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Comment__index" */'@/pages/Comment/index.jsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Type__index" */'@/pages/Type/index.jsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
