// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-access';
export { Provider, useModel } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-access/types.d';
export * from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-antd/types.d';
export * from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-layout/types.d';
export * from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/node_modules/.pnpm/@umijs+renderer-react@4.5.3_ea331d0589dc8c9b1879a3919ebd4dcd/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/node_modules/.pnpm/@umijs+renderer-react@4.5.3_ea331d0589dc8c9b1879a3919ebd4dcd/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/node_modules/.pnpm/umi@4.5.3_@babel+core@7.28._2cdf4eb668d6bc1d484bfe81031bcf27/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
