// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'C:/Users/dengxuan/Desktop/WebStudy-Project/Project/Front-Desk-Project/coder-station/background-system/node_modules/.pnpm/@ant-design+icons@4.8.3_rea_19faa62653f401826ad5c42b19a83e78/node_modules/@ant-design/icons/es/icons/HomeOutlined';
export default { HomeOutlined };
