// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { connect, useDispatch, useStore, useSelector } from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/libs/dva.tsx';
export { getDvaApp } from './dva';
