// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/src/models/adminModel';
import model_2 from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/src/models/typeModel';

export const models = {
model_1: { namespace: 'adminModel', model: model_1 },
model_2: { namespace: 'typeModel', model: model_2 },
} as const
