// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import UserOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import TeamOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import ReadOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ReadOutlined';
import EditOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/EditOutlined';
import ProfileOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
import CalendarOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/CalendarOutlined';
import AppstoreOutlined from 'C:/Users/dengxuan/Desktop/WebStudy/Project/Front-Desk-Project/coder-station/background-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/AppstoreOutlined';
export default { HomeOutlined, UserOutlined, TeamOutlined, ReadOutlined, EditOutlined, ProfileOutlined, CalendarOutlined, AppstoreOutlined };
